name: Sync gh-pages

on:
  push:
    branches:
      - main

jobs:
  sync-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Sync to gh-pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout gh-pages
          git merge main --no-edit
          git push origin gh-pages
